### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by chross** [kenlog/Moon#1]
Hi!
I've installed Moon but my syntax highlighting looks like:
![image](https://user-images.githubusercontent.com/7794409/49520973-b03e5480-f8a4-11e8-9992-2caa5e9bd01f.png)

Any way to fix this or am I missing something?

**Comment by kenlog** [comment]
Hi @chross, try adding matching alias, for example  
` ```sql  `
This [link](https://prismjs.com/#languages-list) can help you learn about the alias.

**Comment by chross** [comment]
Nice, its working now. Thank you for the hint.
