### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by Zelest** [kenlog/Moon#15]
Hey guys,
I just discovered your plugin and I install it on my kanboard but the logo can't load and I don't understand why.
![Sans titre](https://user-images.githubusercontent.com/79452780/178516799-582700df-3a51-4dff-9ccb-d7ca3d8a5e12.png)
Can you help me ?

And thanks for your work :)

**Comment by kenlog** [comment]
Hi @Zelest check it out here https://github.com/kenlog/Moon/issues/9

**Comment by Zelest** [comment]
Thanks have a good day
