### ISSUE TITLE
stat failed for /var/www/app/assets/css/app.min.css

### ISSUE THREAD

**Issue by kristofwillen** [kenlog/Moon#16]
I use this theme since ages, thank you for that.
I recently upgraded kanboard to version 1.2.30, since then the following error message is being displayed on top of each screen:

Warning: filemtime(): stat failed for /var/www/app/assets/css/app.min.css in /var/www/app/app/Helper/AssetHelper.php on line 41

Removing the plugin (theme) removes the error message, so I assume it is an issue in your plugin.  Apart from that, I don't see any other errors in the logs (I use kanboard as docker instance on MacOS).  Reinstalled the plugin, no solution.

**Comment by kenlog** [comment]
Hello @kristofwillen, as soon as I have a chance I will release a new version, in the meantime you can buffer by updating the following [file](https://github.com/kenlog/Moon/blob/master/Template/layout.php)

**Comment by kristofwillen** [comment]
Workaround fixes it, thanks.
