### ISSUE TITLE
Update notifier kept warning about 1.3.6 update, but only 1.3.4 is available

### ISSUE THREAD

**Issue by ghost** [kenlog/Moon#3]
Is it a problem with your current release not updating the version number?

**Comment by kenlog** [comment]
Hi @Plausible0Bug this problem does not appear from my test. If the problem persists I suggest you remove and install the plugin again. In your plugin directory which version is shown in "Moon"?

**Comment by ghost** [comment]
Hi,

I just tried a fresh install of Kanboard and was able to reproduce the error:
```
Application version: 1.2.7
PHP version: 7.2.13
PHP SAPI: fpm-fcgi
OS version: Linux 4.19.3-300.fc29.x86_64
Database driver: mysql
Database version: 10.3.8-MariaDB-1:10.3.8+maria~bionic
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

1. Install Moon 1.3.4 manually.
2. Install UpdateNotifier from plugins management.
3. Try to update Moon to 1.3.6, it will apply but the version number will stuck at 1.3.4, although the local files had been updated.
4. Clearing the browser cache and login/logout will not fix the problem.
5. Restart the server of Kanboard will fix the problem

The update will NOT be applied until the server is restarted.

I hope these can help someone.

**Comment by kenlog** [comment]
This problem only occurs in the docker environment. I assume you're running docker, right @Plausible0Bug ? So it's not about the plug-in, it's about the docker container.

**Comment by ghost** [comment]
Thanks for pointing it out, I'll further investigate it.
