### ISSUE TITLE
Logo mouse hover effect 

### ISSUE THREAD

**Issue by tisoportes** [kenlog/Moon#4]
I cannot get mouse hover effect on logo.  And I didn't change nothing from moon.css

.header img {
  float: left;
}
header {
    display: flex;
    flex-wrap: wrap;
    padding: 5px 10px;
    margin-bottom: 5px;
    border-bottom: 0px solid #dedede;
    padding: 15px 10px;
    margin-bottom: 15px;
    background: #364046;
}

Any idea?

**Comment by kenlog** [comment]
Hello @tisoportes is intentionally inactive, if you want to have the effect on the logo insert going in the settings "Custom Stylesheet" you should get the effect. `.logo a {
    float: left;
}`
