### ISSUE TITLE
default text color on code

### ISSUE THREAD

**Issue by popindavibe** [kenlog/Moon#5]
I have been thoroughly enjoying this theme, however I am bothered by the default text color on generic code blocks: black on dark grey.

My current workaround is to edit and set the block as ` ```shell`, but I would rather have white text for generic blocks.

I tried using Customizer as well but did not find an option to replace that.

**Comment by kenlog** [comment]
Hello @popindavibe thanks for the report, now a [new version ](https://github.com/kenlog/Moon/releases) is available.

**Comment by popindavibe** [comment]
oops, I thinks I commented directly on the commit. So just in case, this did not fix it for me, had to add:
```css
 .markdown code {
    color: #f9fffa
}
```
