### ISSUE TITLE
problem with focus color (black) when dark theme desktop environment

### ISSUE THREAD

**Issue by popindavibe** [kenlog/Moon#7]
Hello,
I activated a dark theme on my desktop, and the problem is that Moon plugin sets black color for text on focus, while not overriding the default background color of the environment.

So every time I enter a form and type in, it's black on dark grey.

We should either drop the overriding of the text, or also override the background in css to get something consistent and and compatible with dark backgrounds.

**Comment by popindavibe** [comment]
I just noticed app.min.css is also hard-setting focus text color to black..

**Comment by kenlog** [comment]
Hi @popindavibe, as you can see I use a dark theme, but I don't find the reported problem.
![theme-black](https://user-images.githubusercontent.com/11728231/57134968-24bfe580-6da8-11e9-93a0-a80f8c9080ca.png)

**Comment by popindavibe** [comment]
hmm, it may be because of Customizer plugin... It says it's compatible with Moon, but the CSS actually don't work well together when both Moon and Customizer are installed. 

On my desktop the form is showing in dark grey, which is more consistent with the idea of a dark desktop environment. I don't remember that Moon is overwriting textarea a form field background, if not I would say it should, since it forces the text in black in those elements.

If it does, then I guess we can close this and it is only a problem of mixing Moon and Customizer.

**Comment by kenlog** [comment]
Yes @popindavibe the Moon theme is compatible with the customizer, but has the condition that "Default" is selected in Manage Themes.

**Comment by popindavibe** [comment]
Oops wrong button.

So here is what I see from my dark theme with Moon and Customizer without touching any of their CSS:

![](https://lutim.nomagic.uk/wALMHN5P)

![](https://lutim.nomagic.uk/AQdHKnuE)

![](https://lutim.nomagic.uk/EZmDbEu1)

**Comment by kenlog** [comment]
I can't simulate what happens in your desktop environment, to fix enter this in the settings -> Custom style sheet `input {
    background-color: #fff;
}` should do the trick :wink:

**Comment by popindavibe** [comment]
Yeah ok, but my point was rather to underline the fact that it would be better to be consistent on the source CSS, either setting text _and_ background colors, or neither of them, so that the theme, either light or dark, handles the display nicely.

**Comment by kenlog** [comment]
Thanks for letting me know, as soon as I can I will work on this and it will be solved with the next release.
