### ISSUE TITLE
Change default path to logo asset

### ISSUE THREAD

**Issue by xoxys** [kenlog/Moon#9]
Kanboard Docker Image prevents loading files fiom /data within nging:

https://github.com/kanboard/kanboard/blob/master/docker/etc/nginx/nginx.conf#L47-L49
```
location ~ /data {
     return 404;
}
```

What do you think about changing the default to `plugins/Moon/Assets/images/brand-logo.png` in your config.php?

**Comment by kenlog** [comment]
@xoxys thanks for reporting, in any case I would like to add the possibility to load the logo directly from the settings panel and exclude the existing system as soon as I have the opportunity.

**Comment by xoxys** [comment]
@kenlog Cool! Sounds good.

**Comment by gerroon** [comment]
It tries to load from here which obviously does not exists and has a broken image link in the board.

`DOMAIN/data/files/Moon/Assets/images/brand-logo.png`

I serve kanboard under `DOMAIN/kanboard/`

So the file is actually under

`DOMAIN/kanboard/plugins/Moon/Assets/images`


I use it under Apache2

**Comment by kenlog** [comment]
Hi @gerroon most likely access to the folder is denied add an `.htaccess` file in the following path `data/files/Moon/Assets/images/` 

Example for Apache
```apache
# Apache 2.2
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
    <Files ~ "(?i)^.*\.(jpg|jpeg|gif|png)$">
        Allow from all
    </Files>
</IfModule>

# Apache 2.4
<IfModule mod_authz_core.c>
    Require all denied
    <Files ~ "(?i)^.*\.(jpg|jpeg|gif|png)$">
        Require all granted
    </Files>
</IfModule>
```
